### ISSUE TITLE
Logo link

### ISSUE THREAD

**Issue by Hojiakbar11** [QuddusbekMahmudov/Quddusbek#1]
Saytni logotipi hardoim link ichida bolishi shart va u index sahifasiga olib borishi kerak
![image](https://github.com/user-attachments/assets/42aa536b-4591-4b4f-b735-7aa4df84b90d)

**Comment by QuddusbekMahmudov** [comment]
Raxmat

**Comment by Hojiakbar11** [comment]
fix #1

**Comment by Hojiakbar11** [comment]
fix #1
